<?php $this->headMeta()->appendName('keywords', 'games, code, javascript, php, jquery'); ?>
<?php $this->headMeta()->appendName('description', 'Games and Code: features javascript games and code developed by Richard Lawson.'); ?>
<?php $this->headTitle()->append('Games and Code - Home'); ?>
<?php $this->headScript()->captureStart() ?>
	$(function(){
		var totalBlogs = 5;
		var noBlogs = 3;
		$('#add-blog').click(function(){
			$('#loadingBlog').show('slow');
			$.post(
		    	'<?php echo $this->url(array(), 'next-blog', true)?>', 
		    	{blogsOnPage: noBlogs},
		    	function(data){
			    	var blogDiv = buildBlogDivFromData(data);
			    	$('#extra-blogs').append(blogDiv);
			    	$('#extra-blogs').show();
		    		$('#loadingBlog').hide();
		    		noBlogs++;
		    		if(noBlogs == <?php echo $this->totalBlogs ?>){
		    			$('#addBlog').hide();
		    		}
		    	}
		    	, 'json'
		    );
		});
		
		function buildBlogDivFromData(blog){
			var blogDiv = '<div class="extra-blog">';
			blogDiv += '<img src="/images/blog-images/' + blog.id + '/thumbnails/' + blog.image + '" alt="' + blog.title + '" style="float:left;padding-right:15px">';
			blogDiv += '<h1>' + blog.title + '</h1>';
			blogDiv += summaryText(blog.summary, 200);
			blogDiv += '<br><br><a href="blog/' + blog.id + '/' + formatForUrl(blog.title) + '" class="more">READ MORE</a>';
			blogDiv += '</div>';
			return blogDiv;
		}
		
		function summaryText(string, maxLength){
			if(string.length > maxLength){
				string = string.substring(0, maxLength);
				string += '...'; 
			}
			return string;
		}
		
		function formatForUrl(str) {
		    return str.replace(/_/g, '-')
		        .replace(/ /g, '-')
		        .replace(/:/g, '-')
		        .replace(/\\/g, '-')
		        .replace(/\//g, '-')
		        .replace(/[^a-zA-Z0-9\-]+/g, '')
		        .replace(/-{2,}/g, '-')
		        .toLowerCase();
		};
		
  });
<?php $this->headScript()->captureEnd() ?>
<div class="slider-wrapper theme-default">
	<div class="ribbon"></div>
    <div id="slider" class="nivoSlider">
    	<img src="/images/nivo-slider/f-14-fighter.jpg" alt="" title="F-14 Fighter: shoot down those pesky Germans." />
    	<img src="/images/nivo-slider/control-panel.jpg" alt="" title="My new admin panel makes good use of AJAX to improve usability." />
    	<img src="/images/nivo-slider/f-14-fighter-facebook.jpg" alt="" title="#facebook-caption" />
		<img src="/images/nivo-slider/doctrine.jpg" alt="" title="Doctrine: used for DB stuff on this blog." />
	</div>
	<div id="facebook-caption" class="nivo-html-caption">
		F-14 Fighter is now on Facebook. <a href="http://apps.facebook.com/tomcat-fighter" target="_blank">Click here</a> to check it out.
	</div>
</div>
<br><br>
<div class="headline">LATEST BLOG ENTRIES</div>
<br>
<div class="home-features">
	<?php $i = 1?>
	<?php foreach($this->blogEntries as $blogEntry):?>
		<?php if($i == 1):?>
			<div class="home-feature-left">
		<?php elseif($i == 2):?>
			<div class="home-feature-middle">
		<?php elseif($i == 3):?>
			<div class="home-feature-right">
		<?php endif?>	
			<?php if($blogEntry->image != ""):?>
				<img src="/images/blog-images/<?php echo $blogEntry->id?>/thumbnails/<?php echo $blogEntry->image?>" alt="<?php echo $blogEntry->title?>"><br/>
			<?php else:?>
				<img src="/images/gq-watches-baume-et-mercier-mens-hampton.jpg2 alt="<?php echo $blogEntry->title?>">
			<?php endif?>
			<div class="category-block<?php echo $i?>"><?php echo strtoupper($blogEntry->category->name)?></div>
			<h1><?php echo $blogEntry->title ?></h1>
			<?php echo $this->summaryText($blogEntry->summary, 130) ?>
			<br><br><a href="<?php echo $this->url(array('id' => $blogEntry->id, 'urlFriendlyName' => $this->prepareUrlText($blogEntry->title)), 'blog', true); ?>" class="more">READ MORE</a>
		</div>
		<?php $i++; ?>
	<?php endforeach ?>
</div>
<div id="extra-blogs"></div>
<div id="loadingBlog">
	<img src="/images/small-facebook.gif" alt="loading">
</div>
<div id="addBlog"><img src="/images/load-more.png" alt="load another blog" id="add-blog" ></div>

