<div class="footer-menu">
	<div class="footer-col">Menu</div><br class="floatfix"/>
	<ul id="footer-menu">
		<li><a href="/">Home</a></li>
		<li><a href="<?php echo $this->url(array(), 'about', true)?>">About</a></li>
		<li><a href="<?php echo $this->url(array(), 'contact', true)?>">Contact</a></li>
	</ul>
</div>
<div class="footer-menu">
	<div class="footer-col">Blog Categories</div><br class="floatfix"/>
	<?php echo $this->render('_categoryMenu.phtml')?>
</div>
