<?php echo $this->doctype() ?>
<html lang="en">
<head>
  <?php echo $this->headMeta(); ?>
  <?php echo $this->headTitle(); ?>
	  <?php $this->headLink()->prependStylesheet('/css/main-basic.css'); ?>
	  <?php $this->headScript()->prependFile('/js/jquery/jquery-1.6.2.js'); ?>
	  <?php $this->headScript()->appendFile('/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9' )); ?>
  <?php echo $this->headLink(); ?>
  <?php echo $this->headScript(); ?>
</head>
<body>
	<div id="wrapper">
		<br/>
  		<?php echo $this->layout()->content ?>
	</div>
</body>
</html>