<?php $this->fetchCategories() ?>
<?php echo $this->doctype() ?>
<html lang="en">
<head>
  <?php echo $this->headMeta(); ?>
  <?php echo $this->headTitle(); ?>
	  <?php $this->headLink()->prependStylesheet('/css/main.css'); ?>
	  <?php $this->headLink()->prependStylesheet('/css/tabs.css'); ?>
	  <?php $this->headLink()->prependStylesheet('/css/nivo-slider.css'); ?>
	  <?php $this->headLink()->prependStylesheet('/css/nivo-themes/default/default.css'); ?>
	  <?php $this->headScript()->appendFile('/js/jquery/jquery.tabs.js'); ?>
	  <?php $this->headScript()->appendFile('/js/jquery/jquery.nivo.slider.pack.js'); ?>
	  <?php $this->headScript()->appendFile('/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9' )); ?>
  	  <?php $this->headScript()->prependFile('/js/jquery/jquery-1.6.2.js'); ?>
  <?php echo $this->headLink(); ?>
  <?php echo $this->headScript(); ?>
  <script>
  $(document).ready(function(){
	$('#slider').nivoSlider();
	  
  	$('#search-button').click(function(){
  	  	if($('#search-term').val() == ''){
			alert('Please enter a search term');
  	  	}else{
  	  		$('#search-form').submit();
  	  	}
  	});

  	$('#send-message').click(function(){
  		$('#confirmation').hide();
  	  	var valid = true;
  	  	var name = $('#name').val();
  	    var email = $('#email').val();
  	    var message = $('#message').val();
  	  	
		if(name == ''){
			valid = false;
			$('#name-required').show('slow');
		}else{
			$('#name-required').hide();
		}

		if(email == ''){
			valid = false;
			$('#email-required').show('slow');
		}else{
			$('#email-required').hide();
			if(!isEmail(email)){
				valid = false;
				$('#email-invalid').show('slow');
			}else{
				$('#email-invalid').hide();
			}
		}
		
		if(message == ''){
			valid = false;
			$('#message-required').show('slow');
		}else{
			$('#message-required').hide();
		}

		if(valid){
			$('#sending-data').show('slow');
			$.post(
		    	'<?php echo $this->url(array(), 'sendmessage', true)?>', 
		    	{name: name, email: email, message: message},
		    	function(data){
			    	if(data.responseStatus == 'INVALID'){
				    	var errString = 'PLEASE CORRECT THE FOLLOWING:<br>';
				    	for(var i = 0; i< data.errors.length; i++){
				    		errString += data.errors[i] + '<br>';
					    }
			    		$('#confirmation').html(errString);
					}else if(data.responseStatus == 'FAILED'){
						$('#confirmation').html('Your message could not be sent. Please try again');
					}else{
						$('#confirmation').html('Your message has been sent.');
					}
		    		$('#confirmation').show('slow');
		    		$('#sending-data').hide();
		    	}
		    	, 'json'
		    );
		}
		
  	});
  	
  });

  function isEmail(email) {
	  var regex = /^([a-zA-Z0-9_\.\-\+])+\@(([a-zA-Z0-9\-])+\.)+([a-zA-Z0-9]{2,4})+$/;
	  return regex.test(email);
  }
  </script>
</head>
<body>
	<div id="header-wrapper">
		<div id="header">
			<div id="header-left">
				<div id="header-top">
					<img src="/images/logo.png" alt="Games and Code"><br/><div style="color:#fff;padding-top:2px;">WWW.GAMESANDCODE.CO.UK</div>
				</div>
				<div id="menu">
					<?php echo $this->render('_topMenu.phtml');?>
				</div>	
			</div>
			<div id="header-right">
				SEARCH BLOGS:<br/>
				<div id="search-box">
					<div id="search-box-left">
						<form method="post" action="<?php echo $this->url(array(), 'search', true)?>" id="search-form"><input type="text" size="30" name="search-term" id="search-term"></form>
					</div>
					<div id="search-box-right">
						<img src="/images/search-button.jpg" alt="keyword Search" id="search-button">
					</div>
				</div>
			</div>
		</div>
	</div>
	<div id="content-wrapper">
		<div id="content">
			<div id="content-left">
		 		<?php echo $this->layout()->content ?>
		 	</div>
		 	<div id="content-right">
		 		<ul class="tabs">
				    <li><a href="#tab1">Blog Categories</a></li>
				    <li><a href="#tab2">Games</a></li>
				    <li><a href="#tab3">Calendar</a></li>
				</ul>
				<div class="tab_container">
				    <div id="tab1" class="tab_content">
				    	<?php echo $this->render('_categoryMenu.phtml');?>
				    </div>
				    <div id="tab2" class="tab_content">
				        <ul class="category-menu">
				        	<li><a href="<?php echo $this->url(array(), 'tomcatfighter', true)?>" target="_blank">F-14 Fighter</a></li>
				    		<li><a href="http://apps.facebook.com/tomcat-fighter" target="_blank">F-14 Fighter on Facebook</a></li>
				    	</ul>
				    </div>
				    <div id="tab3" class="tab_content">
				        Coming Soon ...
				    </div>
				</div>
				<br class="floatfix"><br/>
				<form action="" method="post" name="contactform" id="contactform">
				<div id="contact-form">
					<div class="title">
						CONTACT FORM:
					</div>
					<div class="form-label">
						<span class="form-block">NAME:</span>
					</div>
					<div class="form-row">
						<input type="text" name="name" id="name" size="30">
					</div>
					<div class="form-label-required" id="name-required">
						<span class="form-block-required">name is required:</span>
					</div>
					<div class="form-label">
						<span class="form-block">EMAIL:</span>
					</div>
					<div class="form-row">
						<input type="text" name="email" id="email" size="30">
					</div>
					<div class="form-label-required" id="email-required">
						<span class="form-block-required">email is required:</span>
					</div>
					<div class="form-label-required" id="email-invalid">
						<span class="form-block-required">email is not valid:</span>
					</div>
					<div class="form-label">
						<span class="form-block">MESSAGE:</span>
					</div>
					<div class="form-row">
						<textarea name="message" id="message" cols="28" rows="6"></textarea>
					</div>
					<div class="form-label-required" id="message-required">
						<span class="form-block-required">message is required:</span>
					</div>
					<div class="form-row">
						<img src="/images/send-message.png" alt="send message" id="send-message">
					</div>
					<div class="form-label-data" id="sending-data" >
						<img src="/images/load.gif" alt="sending data" style="margin-bottom:-3px">&nbsp;Sending data to server.
					</div>
					<div class="form-label-data" id="confirmation" >
						Your message has been sent.
					</div>
				</div>
				</form>
		 	</div>
		 	<br class="floatfix">
		</div>
	</div>
	<div id="footer-wrapper">
		<div id="footer">
			<div class="footer-menus">
				<?php echo $this->render('_footerMenus.phtml');?>
			</div>
			<div id="trailer">
				<div id="trailer-left">Games and Code &copy;</div>
				<div id ="trailer-right">Contact: <a href="mailto:richard@gamesandcode.co.uk">richard@gamesandcode.co.uk</a></div>
			</div>
		</div>
	</div>
</body>
</html>