<h1>Search Page</h1>
<?php if(count($this->blogEntries)):?>
	<div class="headline-alt">Search results for: <em><strong>'<?php echo $this->searchTerm ?>'</strong></em></div>
	<br class="floatfix"><br>
	<?php foreach($this->blogEntries as $blogEntry):?>
		<span class="category-block1"><?php echo strtoupper($blogEntry->category->name)?></span>
		<h1><?php echo $blogEntry->title?></h1>
		<h4><?php echo $blogEntry->postDate->format('l jS F Y') ?></h4><br>
		<img src="/images/blog-images/<?php echo $blogEntry->id?>/thumbnails/<?php echo $blogEntry->image?>" alt="<?php echo $blogEntry->title?>" align="left" style="margin-right:20px"> 
		<?php echo nl2br($blogEntry->summary) ?>
		<br><br><a href="<?php echo $this->url(array('id' => $blogEntry->id, 'urlFriendlyName' => $this->prepareUrlText($blogEntry->title)), 'blog', true); ?>" class="more">READ MORE</a>&nbsp;
		<br class="floatfix"><hr>
	<?php endforeach ?>
<?php else:?>
	<p>No blog entries matched your search term: <em><strong>'<?php echo $this->searchTerm ?>'</strong></em></p>
<?php endif?>

